spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false        # 开发时关闭缓存，否则无法实时看到页面效果
    mode: LEGACYHTML5   # 使用非严格的HTML标准
    encoding: UTF-8

mybatis:
  type-aliases-package: com.qf.entity
  mapper-locations: classpath:mapper/*Mapper.xml